# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DropTip <- function(x, extinct) {
    .Call('FARM_DropTip', PACKAGE = 'FARM', x, extinct)
}

NewTip <- function(x, parent, child, branch) {
    .Call('FARM_NewTip', PACKAGE = 'FARM', x, parent, child, branch)
}

