#!/bin/bash
#PBS -N tuff_tester 
#PBS -M tuff@wustl.edu 		
#PBS -m a				
#PBS -V 					
#PBS -l walltime=12:00:00				
#PBS -l pmem=1200mb 
#PBS -l procs=1 
#PBS -t 1-3000


echo $PBS_ARRAYID

cd /home/ttuff/mydirectory
module load R-3.2.1

export R_LIBS=$HOME/rlibs
#R CMD INSTALL --library=/home/ttuff/rlibs  FARM_1.0.tar.gz

Rscript --vanilla ./FARM_four_model_compare_general_trait_UTO.R ${PBS_ARRAYID}
